name: qr_code_scanner_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  barcode_widget: ^1.5.0
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^1.0.1
  get: ^4.6.1
  davinci: 
  image_gallery_saver:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
